application:
    port: 8000
database:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "newsletter"
email_client:
    base_url: "localhost"
    sender_email: "test@gmail.com"
    auth_token: "super-secret-token"
    timeout_millis: 10000